---
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
all:
  hosts:
    localhost:
      ansible_sudo: false
      ansible_connection: local
      ansible_python_interpreter: python
  children:
    web_servers:
      hosts:
        web-server:
    build_servers:
      hosts:
        build-server:
    db_servers:
      hosts:
        db-server:
# vars:
#   # Tell Ansible to use Python 3 on target machines
#   ansible_python_interpreter: /usr/bin/python3
